### ISSUE TITLE
Custom login - registration, whether the configuration field is required to save, and the actual registration page is not required to fill in

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#1014]
自定义登录-注册 ，配置字段是否必填后保存，与实际注册页的是否必填不符，自行检查。
![image](https://user-images.githubusercontent.com/95004531/232651032-c7131b58-d2b8-4653-b8ea-a4d8a64b54a9.png)
![image](https://user-images.githubusercontent.com/95004531/232651061-2a531af5-7c0d-4e7f-a734-682ff2cf3a50.png)

**Comment by zyz** [comment]
#1013

**Comment by LazyEar0** [comment]
此问题仍存在
