### ISSUE TITLE
修改用户账号，当姓名全拼位数少于8个字符，无法修改， 引起其他系统请求token无法请求

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1018]
![image](https://user-images.githubusercontent.com/93168234/232705905-67ff4c0e-4bc4-4789-b134-6d524c6464fe.png)

![image](https://user-images.githubusercontent.com/93168234/232705991-aae318e5-4a8a-40c4-9ad3-764683fda79d.png)

**Comment by doddgu** [comment]
@xie1wei2 PTAL

**Comment by xie1wei2** [comment]
账号4+4 原设计是按照最少4位数英文字母（中式名字拼音最少4位+工号设计）这样可以去重，按照目前的需求有如下2个解决方案
1.保持4+4最少8位，完善原账号内容。
2.去除8位数限制，最少4位以上

**Comment by limei7** [comment]
如果遇到业务问题，IoT只能先手动修改数据库数据
