### ISSUE TITLE
修改头像后， 刷新浏览器， 右上角头像图都会闪一下默认头像，再更新成正确头像

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1019]
![image](https://user-images.githubusercontent.com/93168234/232707604-11cb4e07-d4d7-4736-a7ee-deaa2e4f6411.png)

**Comment by xie1wei2** [comment]
可以复现一下么，录个小视频。我这边查看没有该情况@limei7

**Comment by limei7** [comment]
反馈是 默认头像到时候换一下即可
