### ISSUE TITLE
切换身份，切换到员工， 刷新浏览器， 右上角的头像仍然是用户身份的头像

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1020]
操作步骤， IoT平台测试环境， 
员工身份和用户身份都修改一下头像
切换到员工， 刷新浏览器
发现， 右上角还是用户身份的头像
![image](https://user-images.githubusercontent.com/93168234/232708205-2173aa13-6c44-47c2-82f9-f7adde356c36.png)

**Comment by limei7** [comment]
切不过来身份

**Comment by xie1wei2** [comment]
收到，查验确实有这样情况。安排修复

**Comment by xie1wei2** [comment]
这里不是真实切换身份，你依然是员工的身份。但是可以切换查看用户！不是真实切换到员工身份，如果切换过去你可能前面的功能权限都会丢失了。个人与员工的权限是不同的

**Comment by doddgu** [comment]
> 这里不是真实切换身份，你依然是员工的身份。但是可以切换查看用户！不是真实切换到员工身份，如果切换过去你可能前面的功能权限都会丢失了。个人与员工的权限是不同的

翻译一下：这里只是查看个人资料是查看用户资料还是员工资料而已。

> 至于权限丢失是不会的，因为统一都是用户权限，不管是不是员工。因为你还是你，不管你是用户还是员工，你是不会变的。

**Comment by limei7** [comment]
已了解
