### ISSUE TITLE
用户身份，编辑修改信息， 保存按钮无法保存

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1021]
IoT平台测试环境
登录后， 切换到用户， 编辑修改信息， 保存按钮无法启用
![image](https://user-images.githubusercontent.com/93168234/232716290-beb57be5-d93c-45a5-b637-cb1b89002cdd.png)

**Comment by xie1wei2** [comment]
@limei7  我这边没有这样的情况

**Comment by MayueCif** [comment]
姓名不能为空
