### ISSUE TITLE
IoT平台上操作部分功能按钮时，接口调用成功后，刷新页面的过程中，会被自动跳出到登录页

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1036]
比如， IoT测试环境， 登录成功后， 在浏览器（chrome或者edge都有出现）停留几分钟，比如10分钟， 再操作 解绑序列号、绑定序列号、修改安装单等功能， 在接口调用成功后， 页面刷新的过程中， 账号会被自动跳出到登录页

![image](https://user-images.githubusercontent.com/93168234/233552224-1cc69c7a-59e7-468b-8385-1789bc028751.png)

![image](https://user-images.githubusercontent.com/93168234/233552249-bac49bcf-c46e-4978-86d8-67fc804cd9fb.png)

**Comment by doddgu** [comment]
issue可以统一先给 谢1伟2，让他先看 @xie1wei2

**Comment by limei7** [comment]
已修复
