### ISSUE TITLE
User list, Autocomplete profile picture does not match the actual profile picture

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#1044]
用户列表，Autocomplete的头像与实际头像不符
![image](https://user-images.githubusercontent.com/95004531/233823163-c1003d39-c395-44d4-bca8-8bb6014fe79a.png)
![image](https://user-images.githubusercontent.com/95004531/233823184-533dc992-b7f8-44a0-8d31-4c30aff8c4d3.png)

**Comment by limei7** [comment]
头像传不了， 暂时无法验证

**Comment by MayueCif** [comment]
> 头像传不了， 暂时无法验证

已解决

**Comment by limei7** [comment]
![Uploading image.png…]()
