### ISSUE TITLE
Edit role, role inheritance text box is truncated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#1046]
编辑角色，角色继承文本框被截断
![image](https://user-images.githubusercontent.com/95004531/233834847-47908bb2-c359-42a2-a256-a0b00baf8428.png)

**Comment by xyfy** [comment]
#1077 
![图片](https://user-images.githubusercontent.com/7838147/237023680-211ae75b-263f-4975-b9d7-7afa6dece5a4.png)
