### ISSUE TITLE
auth-staging无法新建用户并选择角色，选择角色的弹窗自动被关闭

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1063]
![image](https://user-images.githubusercontent.com/93168234/234442056-71b6a176-f12b-4130-8b00-6347ed75d42c.png)
![image](https://user-images.githubusercontent.com/93168234/234442071-7bc00ca8-b98e-428e-993f-b2e0462fdbed.png)

**Comment by LazyEar0** [comment]
组件问题，关联issue： https://github.com/masastack/MASA.Stack.Components/issues/582
