### ISSUE TITLE
Custom login, form validation has replaced the text format

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#1128]
自定义登录-基础信息，当名称和标题输入的文本未通过表单格式验证，Ctrl+V ,粘贴符合验证要求的文本后，文本框仍弹出替换内容的表单验证提示
![image](https://github.com/masastack/MASA.Auth/assets/95004531/bec8e2c9-b959-40aa-9cbb-1c457d4b8847)
![image](https://github.com/masastack/MASA.Auth/assets/95004531/cec2ae79-6eea-44e5-bf70-b368b551168a)

**Comment by masastack-opensource** [comment]
最新状态为不校验，需要重新修复
