### ISSUE TITLE
Global navigation has permissions, toggle project menu 403

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#1137]
用户 鱼丸 ，全局导航有权限，切换项目菜单403
![image](https://github.com/masastack/MASA.Auth/assets/95004531/380b9ac9-6789-48ed-ac75-137ad2098984)
![image](https://github.com/masastack/MASA.Auth/assets/95004531/69b2a656-895d-407e-a4fe-047f1e98a536)

**Comment by limei7** [comment]
还是
![image](https://github.com/masastack/MASA.Auth/assets/93168234/640f54e1-abd4-446e-992a-6f609a804f23)
用我的账号登录后，我实际是有权限的，但是我登录不进去auth

**Comment by MayueCif** [comment]
无法重现

**Comment by limei7** [comment]
retest ok , 所有7个系统都可以正常切换
