### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 394988736** [masastack/MASA.Auth#1146]
![image](https://github.com/masastack/MASA.Auth/assets/81234257/de00e62c-a42e-4186-a149-c1dbd61c6955)
一直启动不了，封装太严重了，想调试都调不了！

**Comment by MayueCif** [comment]
目前auth 无法单独启动，服务间有依赖。需要启动pm->dcc->auth。这个目前是最小集合

**Comment by masastack-opensource** [comment]
暂无才分auth的计划
