### ISSUE TITLE
输入手机号，查询收件人匹配成功时，多余出来一串电话需要手动删除

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1159]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/bd892854-6758-470f-9dc6-e0233d8f397a)

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/845f76ce-3560-494a-a9bb-1fd47d5ce847)

**Comment by MayueCif** [comment]
> 输入姓名去查询， 也是会多出来一串姓名，还需要用户再去手动删除， 比较麻烦

组件行为就是这样的，失去焦点后会清空输入的查询内容
