### ISSUE TITLE
无法通过微信登录

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1161]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/baab2ce9-fb9b-4d6e-aed5-b9db9f45cebe)

**Comment by MayueCif** [comment]
微信登录配置问题，已增加正确配置

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/1b8601d9-1fb3-423b-a821-a3bcfc55b2b7)
