### ISSUE TITLE
登录页iframe遮挡住了下方的备案文字

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1166]
100% chrome浏览器下
![image](https://github.com/masastack/MASA.Auth/assets/93168234/f1948a79-231b-4620-a96b-a22657233f5f)

**Comment by wzh425** [comment]
请提供您的分辨率和 缩放大小配置
![image](https://github.com/masastack/MASA.Auth/assets/13762077/9c4d08fd-ee20-4877-b61f-31e0639e5676)

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/1d247b03-42e9-4e6c-9670-79ea6180334f)

**Comment by limei7** [comment]
已修复
