### ISSUE TITLE
Current users deleted their roles,  he should not have permission after refresh browser

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1181]
当前用户把自己所属角色删除后，刷新浏览器，不应该有权限
![image](https://github.com/masastack/MASA.Auth/assets/93168234/6a6de7dd-54ce-4e0d-9787-23cce840cf9a)

**Comment by MayueCif** [comment]
未复现

**Comment by masastack-opensource** [comment]
设计如此，要求重新登录
