### ISSUE TITLE
After disabling the permission, the role configuration should not be able to select that permission

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1183]
禁用掉权限后，角色详情配置不应该能选到该权限
![image](https://github.com/masastack/MASA.Auth/assets/93168234/37e61451-314d-4a6b-bd13-3740dfdbede6)

**Comment by MayueCif** [comment]
目前设计如此

**Comment by masastack-opensource** [comment]
在权限配置菜单中仍会出现已禁用的菜单项

**Comment by limei7** [comment]
元素权限禁用后， 没有生效， 团队编辑，选择权限时还能看到

**Comment by limei7** [comment]
已修复
