### ISSUE TITLE
当用户头像被修改时，配置团队成员选择用户时，头像未更新

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Auth#1194]
![企业微信截图_16898468605678](https://github.com/masastack/MASA.Auth/assets/93168234/4c35ab43-8f34-4496-9bcf-f50b69358f6f)

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/0fdf5337-d920-4402-9337-793a6ac7105c)

**Comment by MayueCif** [comment]
这里显示的是对应员工的头像
