### ISSUE TITLE
第三方用户域账号同步超时

### ISSUE THREAD

**Issue by masastack-opensource** [masastack/MASA.Auth#1279]
![image](https://github.com/masastack/MASA.Auth/assets/82495610/8e02188d-d7e3-4824-99dd-f547078202b6)
可以考虑异步执行

**Comment by wzh425** [comment]
使用BackgroundJob

**Comment by wzh425** [comment]
#1285

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/231cdb04-73ed-4708-8137-e545f0c82050)
已修复
