### ISSUE TITLE
团队新增/编辑时，选取人员后，清空输入框

### ISSUE THREAD

**Issue by masastack-opensource** [masastack/MASA.Auth#1280]
![image](https://github.com/masastack/MASA.Auth/assets/82495610/89d8ae90-5f5a-4d0d-b625-d4d1372fb1f9)

**Comment by wzh425** [comment]
> ![image](https://private-user-images.githubusercontent.com/82495610/322716977-89d8ae90-5f5a-4d0d-b625-d4d1372fb1f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDUxMjAsIm5iZiI6MTcxMzk0NDgyMCwicGF0aCI6Ii84MjQ5NTYxMC8zMjI3MTY5NzctODlkOGFlOTAtNWY1YS00ZDBkLWI2MjUtZDRkMTM3MmZiMWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA3NDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjJhOTgxOTE3YTc3MDIxZDMxNjBkNDQ1OTg1ZTc5MDk2YmI0NmI5OTczYzQ4YzMyM2E1NDA2YjAwYzdlMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDkgriVyFslQWctykVRd6Xc3a-zHVtRjxKvOcc1W8iI)

Supports multiple selection and needs to be cleared after losing focus

**Comment by limei7** [comment]
不是问题
