### ISSUE TITLE
Employees . Employee synchronization failure

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#173]
同步员工失败
![image](https://user-images.githubusercontent.com/95004531/178884059-e25092ad-14dc-4e84-b3dc-3a30e6699ed8.png)

![image](https://user-images.githubusercontent.com/95004531/178884049-3b3ab66f-5127-475f-ba6f-2ad22b7c87b0.png)

上传的文件如下：
[员工模板.txt](https://github.com/masastack/MASA.Auth/files/9107843/default.txt)
[StaffSyncTemplate.csv](https://github.com/masastack/MASA.Auth/files/9107846/StaffSyncTemplate.csv)

**Comment by 15168440402** [comment]
文件必须是UTF-8格式，报错提示已修复，会提示使用UTF-8格式文件

**Comment by LazyEar0** [comment]
resolved
