### ISSUE TITLE
Organizational structure . The department's search is invalid

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#178]
组织架构 - 部门的搜索无效
![image](https://user-images.githubusercontent.com/95004531/178892585-4c9043f7-7ed6-462d-bd13-6adebffeefca.png)

**Comment by MayueCif** [comment]
下次提测版本更新此问题

**Comment by LazyEar0** [comment]
部门搜索功能缺失
![image](https://user-images.githubusercontent.com/95004531/183592525-f6a704bc-011e-4b61-bca0-e57638b0f576.png)

**Comment by LazyEar0** [comment]
resolved
