### ISSUE TITLE
User . A deleted user cannot access the login page

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#181]
当用户被删除后，已删除的用户无法进入到登录页面
![image](https://user-images.githubusercontent.com/95004531/178904663-b58d1df1-1435-42b1-81ca-3c85d3d9cd81.png)

**Comment by MayueCif** [comment]
删除用户增肌了超级管理员和当前用户的限制

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/179456815-57b53e91-44eb-467d-b537-8b0746225b22.png)
删除用户报错

**Comment by LazyEar0** [comment]
resolved
