### ISSUE TITLE
  user--advanced search

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.Auth#21]
![image](https://user-images.githubusercontent.com/102500164/163771048-40548426-787b-4f65-85e6-ab8ff7d131ca.png)

预期结果：1点击高级搜索显示的功能     2点击高级搜索按钮会高亮显示
实际结果：1高级搜索功能缺失        2点击高级搜索按钮未显示高亮

**Comment by 15168440402** [comment]
The icon in the ui will not be highlighted, and the icon will be switched to achieve the switch icon
