### ISSUE TITLE
Permissions  . Element permissions are not displayed in the permission list after being added successfully

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#225]
根菜单下，元素权限添加成功后，没有显示在权限列表
![image](https://user-images.githubusercontent.com/95004531/182276021-7b8e0bd0-640d-4a22-b53c-0023492be3ca.png)

**Comment by MayueCif** [comment]
限制为根级只能添加菜单权限

**Comment by LazyEar0** [comment]
resolved
