### ISSUE TITLE
Role . Error reported when popover is closed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#231]
多次点击新增按钮，关闭弹窗，页面报错
![企业微信截图_16594177437399](https://user-images.githubusercontent.com/95004531/182298929-fb5e1b5c-bd59-4ad3-a35b-2b5972ec57c1.png)

**Comment by 15168440402** [comment]
already fixed

**Comment by LazyEar0** [comment]
resolved
