### ISSUE TITLE
Role . The check box is not selected correctly

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#232]
子级取消选中后，父级应为未选中状态
![image](https://user-images.githubusercontent.com/95004531/182301942-557d3e32-c75c-43e0-a54a-c3f96fefaa62.png)

**Comment by 15168440402** [comment]
子级和父级直接没有这个交互关系，父级是代表着有这个页面的查看权限，而子集是操作权限，子集没有勾选，父级是可以选中的

**Comment by LazyEar0** [comment]
resolved
