### ISSUE TITLE
Permissions . The permissions of roles and permissions cannot be configured

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#235]
设置用户/角色/团队权限时，不显示菜单权限“角色”和"权限"
![image](https://user-images.githubusercontent.com/95004531/182305210-2f9d6065-20ce-4a93-b333-b6b625973ef2.png)
![image](https://user-images.githubusercontent.com/95004531/182305289-1b8467a5-f183-45b6-99f1-dd6e77d63263.png)

**Comment by 15168440402** [comment]
需要限制菜单下不能同时存在元素和菜单

**Comment by LazyEar0** [comment]
resolved
