### ISSUE TITLE
User . After user data is modified, it is not synchronized to employees. 

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#238]
前提条件：
已有用户，且为员工；
操作步骤：
修改用户数据后，切换至员工列表及部门员工列表查看该用户数据；
实际结果：
员工列表及部门员工列表未同步更新用户列表中修改的数据
![image](https://user-images.githubusercontent.com/95004531/182315611-974c5ba4-1a39-4f55-9d97-082d29c26fe0.png)
![image](https://user-images.githubusercontent.com/95004531/182316157-d3fdfabd-06ae-4b73-a958-56c22d2e5a7c.png)
![image](https://user-images.githubusercontent.com/95004531/182316254-77969ead-8088-4f7c-a8e5-cc014644a5f8.png)

P.s.同理，修改员工数据后，用户列表的数据未同步更新

**Comment by 15168440402** [comment]
The underlying data of employees and users is separate and not shared

**Comment by LazyEar0** [comment]
员工信息与用户信息不互通，需要分别编辑。
