### ISSUE TITLE
User . Edit staff, the reset password function is invalid

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#240]
编辑员工，重置密码后，仍可用原密码登录，使用新密码登录，提示密码错误

![image](https://user-images.githubusercontent.com/95004531/182317950-ddd2e182-368e-4b65-bc6e-74f99b24eb74.png)
![image](https://user-images.githubusercontent.com/95004531/182318054-45b4a08c-56c6-4a83-af64-212b1248bc25.png)

**Comment by 15168440402** [comment]
The staff page has removed the user password field

**Comment by LazyEar0** [comment]
编辑员工无重置密码功能
