### ISSUE TITLE
User . TAB toggles do not automatically update the list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#262]
员工tab新增员工后，切换至用户tab，没有更新用户列表，需要刷新网页才更新用户列表
![image](https://user-images.githubusercontent.com/95004531/184093234-c9832282-75aa-497b-b40b-084512e56cee.png)
![image](https://user-images.githubusercontent.com/95004531/184093253-7f71b748-bd59-44de-8aee-0786fa981a3a.png)

**Comment by 15168440402** [comment]
@capdiem 需要曹优先支持

**Comment by LazyEar0** [comment]
resolved
