### ISSUE TITLE
User . The employee list user name is incorrect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#265]
员工列表应显示员工姓名， 现显示员工昵称
实际结果：
![image](https://user-images.githubusercontent.com/95004531/184095875-cc9040b0-4791-47bc-9a38-cd6bad288706.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/184095948-e4855b7f-aabc-4a2a-8100-e1f1fc177cbc.png)

**Comment by 15168440402** [comment]
@xie1wei2  产品后面将需求改为所有地方统一展示昵称

**Comment by LazyEar0** [comment]
resolved
