### ISSUE TITLE
 user- add new users

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.Auth#27]
![image](https://user-images.githubusercontent.com/102500164/163910933-71a06927-d35b-471f-95df-4b76b2e5688a.png)

预期结果：必填项未填写点击提交，提示填写必填项
实际结果：必填项未填写点击保存，未提示

**Comment by 15168440402** [comment]
> ![image](https://user-images.githubusercontent.com/102500164/163910933-71a06927-d35b-471f-95df-4b76b2e5688a.png)
> 
> 预期结果：必填项未填写点击提交，提示填写必填项 实际结果：必填项未填写点击保存，未提示

Due to changes in demand, name and mobile phone number and email address are not required.
