### ISSUE TITLE
User . The submission domain account lacks loading

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#297]
域账号弹窗，提交后，应增加Loading
![image](https://user-images.githubusercontent.com/95004531/189081633-7068280f-45c1-465e-80d8-341b48bc1fc4.png)

**Comment by LazyEar0** [comment]
Loading加在页面层，加载状态时，不可以操作关闭弹窗

**Comment by MapleWithoutWords** [comment]
该效果还没设计
![image](https://user-images.githubusercontent.com/38368335/224967958-335b949a-0f1d-426e-abba-2dbb44ab2293.png)
