### ISSUE TITLE
User . Adjust the spacing at the bottom of the user list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#299]
用户列表底部与分页器间距过大
![image](https://user-images.githubusercontent.com/95004531/189098501-c16035fc-9cbe-4bde-bb7c-4bb567d88b27.png)

**Comment by 15168440402** [comment]
1080 分辨率已正常，高分辨率下还是是会出现这种情况的

**Comment by 15168440402** [comment]
@xie1wei2
