### ISSUE TITLE
Registered .  The user registration protocol is missing.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#310]
注册，《用户申请注册协议》点击后，应显示用户申请注册协议，现与复选框联动
![image](https://user-images.githubusercontent.com/95004531/191239395-d9e8c5c8-7a42-4d4d-9648-2e0fc53c075d.png)

**Comment by MayueCif** [comment]
[Blazor issues 811](https://github.com/BlazorComponent/MASA.Blazor/issues/811)
等待组件修复
