### ISSUE TITLE
User . If a user is added successfully, refresh the list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#320]
搜索后，点击“新增”用户，用户新增成功后，新增用户弹窗关闭，返回用户列表，应刷新列表，显示最新的用户列表；目前仍停留在搜索结果
![image](https://user-images.githubusercontent.com/95004531/191261299-9ee574a8-55d8-43b2-8557-c2f9b783ad62.png)

**Comment by 15168440402** [comment]
如果用户有设置搜索，我这边则会根据搜索条件搜索页面，不会主动去移除用户的搜索条件

**Comment by LazyEar0** [comment]
resolved
