### ISSUE TITLE
User . Finding a third party user should be searched in the third party user table

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#321]
第三方用户列表的搜索，应在第三方用户列表查找，现在用户表查找
![image](https://user-images.githubusercontent.com/95004531/191395416-a32045c7-1b11-4c7c-b7ed-e3901be86d3d.png)

**Comment by 15168440402** [comment]
这两个页面的用户搜索是同一个搜索，因为第三方用户的数据来源于用户

**Comment by LazyEar0** [comment]
resolved
