### ISSUE TITLE
User . The pop-up window of a new user is abnormal

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#325]
新增用户进入到步骤二
![image](https://user-images.githubusercontent.com/95004531/191433665-07614eb3-a902-48b1-9bd8-bd08e5cc2305.png)
在步骤二停留一段时间后，会自动跳转至步骤一
![image](https://user-images.githubusercontent.com/95004531/191433699-99cfa41d-e0a5-4218-a21e-7918e953f9ab.png)

**Comment by 15168440402** [comment]
@capdiem

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by LazyEar0** [comment]
重复issue
