### ISSUE TITLE
User . Item type error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#338]
项目类型没有Uncategorized
![image](https://user-images.githubusercontent.com/95004531/191884448-897c572c-4904-4f71-ba30-30f78b69c591.png)

**Comment by 15168440402** [comment]
有些应用没有分类，就放在了Uncategorized类型里

**Comment by LazyEar0** [comment]
这里获取项目的项目类型字段，项目类型在创建项目时为必选项，不会存在为空的情况

**Comment by LazyEar0** [comment]
resolved
