### ISSUE TITLE
User . Unselectable role, style adjustment

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#348]
当角色的绑定限制次数达到上限时，用户选择角色的下拉框中，该角色应为置灰不可选中的样式
![image](https://user-images.githubusercontent.com/95004531/192754269-e9933951-c18e-4c6d-bcb9-c14b38c6776f.png)

**Comment by 15168440402** [comment]
之前站会讨论结果是可以点击，但会提示无法选择的原因

**Comment by LazyEar0** [comment]
resolved
