### ISSUE TITLE
 staff-Add employees

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.Auth#35]
![image](https://user-images.githubusercontent.com/102500164/163942816-a8a6e79d-7d1c-437b-b4ef-1315d3fa084c.png)
预期结果：添加员工没有输入昵称点击保存应有提示
实际结果：添加员工没有输入昵称点击保存未提示

**Comment by doddgu** [comment]
@xie1wei2

**Comment by 15168440402** [comment]
Fixed, nickname changed to required

**Comment by LazyEar0** [comment]
现昵称为必填项
