### ISSUE TITLE
Role . If the letters of the role code are repeated and the case is inconsistent, an error is reported

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#361]
已有角色的code为“JS”，再次新增角色，code为“Js”，提交时报错
![image](https://user-images.githubusercontent.com/95004531/193230888-86eec7a2-2365-411b-a1e0-16c8a5ca4517.png)

**Comment by 15168440402** [comment]
![image](https://user-images.githubusercontent.com/30889371/194742172-992a15d8-6133-43d0-bb75-b68233399bdd.png)

**Comment by LazyEar0** [comment]
角色code区分大小写，当已有角色的code为“JS”时，再次添加角色，code为“js”，应提交成功，先空提示，无法提交.
![image](https://user-images.githubusercontent.com/95004531/195515055-734c95a6-ac51-4807-8b8c-03c93c2c51e8.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by LazyEar0** [comment]
resolved
