### ISSUE TITLE
Permissions . When the user/role with the permission is empty, the status of the input box is adjusted

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#371]
当权限的使用者/使用角色为空时，输入框的标签应与上方“挂靠API权限”的状态保持一致
![image](https://user-images.githubusercontent.com/95004531/194751711-1b6a33bf-592c-435d-bffe-522e83359a7f.png)

**Comment by MayueCif** [comment]
这是两种不懂得组件，使用者/使用角色 更像一种分组，挂靠API权限是select 组件
