### ISSUE TITLE
Team . The edit team removed the preview feature

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#377]
编辑团队去掉“预览”按钮
![image](https://user-images.githubusercontent.com/95004531/194814693-83c43625-c503-4560-ae6f-fa2b284297c1.png)
![image](https://user-images.githubusercontent.com/95004531/194814734-dde7894f-ef16-4c54-834b-37ce0bc5e1bd.png)

**Comment by MayueCif** [comment]
确认过要有预览按钮
