### ISSUE TITLE
Permissions . Permissions are not quarantined by team

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#395]
用户的权限没有根据所选的团队进行隔离。如 团队“权限”，仅包含 Auth - 权限 菜单的权限，在PM项目中，选择团队“权限”，页面应是无权限访问的样式
![image](https://user-images.githubusercontent.com/95004531/195268715-7835e05c-5486-4332-825c-22d3cb2da4c8.png)

**Comment by MayueCif** [comment]
[duplicate](https://github.com/masastack/MASA.Stack.Components/issues/215)
