### ISSUE TITLE
Time selector. Reset should clear data directly

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#402]
时间选择器，时分秒有值时，点重置按钮，会先重置时分秒。应直接清除日期 + 时间
![image](https://user-images.githubusercontent.com/95004531/195298050-26bc0d28-6c14-4e4a-a445-8d26001f6d7a.png)
![image](https://user-images.githubusercontent.com/95004531/195301326-b5db6d02-e03a-4d41-8378-254f35bf8aca.png)

**Comment by 15168440402** [comment]
初步判断是曹优先那边组件的bug导致这个问题

**Comment by LazyEar0** [comment]
resolved
