### ISSUE TITLE
Login . The phone number format error should be prompted when the button is triggered

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#430]
当手机号码的格式错误时，在点击“获取短信验证码”时提示用户，在用户输入的过程中，不需要提示。
![image](https://user-images.githubusercontent.com/95004531/196580371-a09621fa-d79a-423d-bf26-2546945f159a.png)

**Comment by MayueCif** [comment]
目前组件验证逻辑如此
