### ISSUE TITLE
User . Failed to synchronize employee data. 

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#439]
同步员工模板失败
![image](https://user-images.githubusercontent.com/95004531/196621839-2fdb0337-c75e-4605-b5cb-188966c26ca1.png)

上传的文件：
[StaffSyncTemplate (3).csv](https://github.com/masastack/MASA.Auth/files/9817764/StaffSyncTemplate.3.csv)

**Comment by 15168440402** [comment]
序号必填

**Comment by LazyEar0** [comment]
上传员工模板报错：
文件为
[StaffSyncTemplate (4).csv](https://github.com/masastack/MASA.Auth/files/9856786/StaffSyncTemplate.4.csv)

![image](https://user-images.githubusercontent.com/95004531/197672369-2f6589c4-3360-47c0-bf4f-c464b360f32c.png)

**Comment by LazyEar0** [comment]
resolved

**Comment by LazyEar0** [comment]
上传员工模板报错
上传文件：
[StaffSyncTemplate (4).csv](https://github.com/masastack/MASA.Auth/files/9866797/StaffSyncTemplate.4.csv)

![image](https://user-images.githubusercontent.com/95004531/197952455-cec0b285-21e1-4b6f-934f-b7cce3eb48f0.png)

**Comment by LazyEar0** [comment]
resolved
