### ISSUE TITLE
Team . Team members need to be limited in choosing roles

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#471]
团队成员的角色，仅可选择 团队管理员所选的角色及其继承的角色
![image](https://user-images.githubusercontent.com/95004531/197741804-3d03002b-24c4-4a89-9615-61da87cc7929.png)

**Comment by MayueCif** [comment]
与产品沟通后为成员角色限制为管理员所选角色，不考虑继承角色

**Comment by LazyEar0** [comment]
暂无限制
