### ISSUE TITLE
User . An error occurs when you search for a deleted user

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#496]
用户列表，搜索已删除的用户，列表搜索结果应显示没有数据，现无响应。且再次搜索其他用户时，存在吞字现象
![image](https://user-images.githubusercontent.com/95004531/198942588-cfac7584-a827-42f4-baf8-c71469b02782.png)

**Comment by 15168440402** [comment]
无法复现

**Comment by 15168440402** [comment]
@capdiem 需要配合看看Autocomplete组件
