### ISSUE TITLE
User . Status filtering item, cannot view all users

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#533]
用户列表，筛选用户状态时，选择全部用户无效
![image](https://user-images.githubusercontent.com/95004531/199925317-2e7ef6c3-b26b-46db-8158-026a88b0738c.png)

**Comment by 15168440402** [comment]
@capdiem 需要看看MSelect无法选择默认值的问题

**Comment by LazyEar0** [comment]
resolved
