### ISSUE TITLE
Cached data exists after user permissions are changed. 

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#544]
用户菜单权限发生变化后，APP bar 的菜单搜索，存在缓存，搜索不到新增加的菜单权限
![image](https://user-images.githubusercontent.com/95004531/200771053-e65449cd-8d10-4c0b-9026-7d0de5f3479e.png)

**Comment by LazyEar0** [comment]
此问题仍存在
![image](https://user-images.githubusercontent.com/95004531/204210010-1ececee3-b1dd-4def-a311-69f7c8d36061.png)

**Comment by MayueCif** [comment]
没有地址得菜单不会展示在搜索框里
