### ISSUE TITLE
SSO . Multi-line text boxes must be filled with no prompt

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#575]
用户声明，新增/编辑用户声明时，未填写“描述”点击提交/保存，页面无反应。应提示用户描述是必填项。
![image](https://user-images.githubusercontent.com/95004531/204976427-0da504ab-1018-4b44-ae3f-1a3a416b9a16.png)

**Comment by MayueCif** [comment]
[Masa Blazor](https://github.com/BlazorComponent/MASA.Blazor/issues/825)
