### ISSUE TITLE
SSO . The memory cache was not updated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#583]
身份资源，API范围，API资源，禁用后再启用，仍提示invalid scope
内存缓存没有更新

**Comment by limei7** [comment]
把启用改成禁用，有的时候生效， 有的时候不生效， 而且排序还会变化
![image](https://github.com/masastack/MASA.Auth/assets/93168234/21c55d3f-e35b-42bd-8a3a-8346e98d134c)

**Comment by limei7** [comment]
可能是有延迟； 有时候要改两次才能改过来； 有时候改一次就能改过来

**Comment by limei7** [comment]
依次去修改：这5个名称， 当你修改到第3个的时候， 会发现不生效

**Comment by limei7** [comment]
已修复
