### ISSUE TITLE
User . Add/edit staff and select department to report errors

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#586]
新增/编辑员工，选择部门报错
![image](https://user-images.githubusercontent.com/95004531/205198795-df36caf2-ebd1-4533-874f-dc193b350b36.png)

![image](https://user-images.githubusercontent.com/95004531/205198728-2635472f-a5e7-473e-8c04-73a29da368e5.png)

**Comment by 15168440402** [comment]
@capdiem look
