### ISSUE TITLE
Permissions. After menu permissions are selected, child element permissions are not selected

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#588]
配置权限页，选择某一菜单权限后，下级的元素权限应不被选中
![image](https://user-images.githubusercontent.com/95004531/205221616-defcbf5f-7424-4297-9598-38be5c503522.png)

**Comment by 15168440402** [comment]
需求就是子元素权限需要被全部选中

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by binwan-dev** [comment]
三级菜单出现问题
