### ISSUE TITLE
User . Error verification prompt when synchronizing employee data

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#619]
同步员工时，上传的文件数据发生错误，上传结果页面会出现多个不存在的错误提示
如上传附件文件，实际错误是修改了12行的工号字段，实际上传后的错误信息，是其他行身份证错误，账号错误等信息，没有提示工号不可以修改
上传的文件：
[StaffSyncTemplate (19).csv](https://github.com/masastack/MASA.Auth/files/10205920/StaffSyncTemplate.19.csv)

![image](https://user-images.githubusercontent.com/95004531/206994723-7932b826-712b-4d12-b92e-c8e39d118931.png)

**Comment by 15168440402** [comment]
工号被修改是后续的操作，我是先做表单验证的，表单验证值检查数据格式要求

**Comment by LazyEar0** [comment]
模板中没有账号字段，出现了账号输入大于等于4个字符提示
