### ISSUE TITLE
Organization, the menu will open in the upper left corner

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#636]
组织架构，会出现菜单在左上角打开的情况
![image](https://user-images.githubusercontent.com/95004531/210339942-26fbd2d8-fabc-4083-9d79-5dd6f676f029.png)

![image](https://user-images.githubusercontent.com/95004531/210339043-3a757f4f-8581-4e5d-8ff2-5f8ba15083f9.png)

**Comment by limei7** [comment]
OK
