### ISSUE TITLE
The size of the file limit should be converted according to the unit

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#652]
文件限制大小应根据单位换算，大于1M以M为单位显示，大于1G以G为单位显示，以此类推。
![image](https://user-images.githubusercontent.com/95004531/211725480-4eb484be-7fab-49eb-8b1a-38d500d5b52d.png)

**Comment by 15168440402** [comment]
@xie1wei2 确定excel文件大小限制为多大

**Comment by xie1wei2** [comment]
1M=1024kb，统一以M单位显示大小。

**Comment by LazyEar0** [comment]
@wuweilaiya  @xie1wei2   请确认单位是 “Mb” （Mbit）还是“MB”（MByte）？
实际结果：
![image](https://user-images.githubusercontent.com/95004531/223670463-45ad96d4-039d-4c6e-b1ec-3609c602ef0d.png)

**Comment by zyz** [comment]
#857 Fix: File size unit changed to MB
