### ISSUE TITLE
Error data is not fully displayed after employee synchronization fails.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#655]
员工同步失败后，错误数据显示不全。

![image](https://user-images.githubusercontent.com/95004531/211727027-89122f5f-8c75-457b-9c25-48e390f93824.png)
![image](https://user-images.githubusercontent.com/95004531/211728021-59d387c2-350d-46ce-98da-9f352e6b4ddf.png)

上传文件：
[StaffSyncTemplate (21).csv](https://github.com/masastack/MASA.Auth/files/10389212/StaffSyncTemplate.21.csv)

**Comment by LazyEar0** [comment]
Excel表格身份证格式不对的问题，需再在其他电脑测试一下

**Comment by 15168440402** [comment]
已解决校验问题，用户是否重复是通过表单校验后的步骤，不会与表单校验一起出现
