### ISSUE TITLE
The test environment Autocomplete cannot search for data

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#658]
测试环境Autocomplete 搜索不到数据，开发环境搜索admin，查询的是测试环境的数据
![image](https://user-images.githubusercontent.com/95004531/211737356-960114a3-9986-4d32-b05c-9e1e5b82f299.png)

**Comment by LazyEar0** [comment]
隔离性问题

**Comment by limei7** [comment]
OK
