### ISSUE TITLE
Third party user list, creator error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#659]
第三方用户列表，创建人错误，优先显示创建者的员工昵称，无员工昵称则显示用户昵称
![image](https://user-images.githubusercontent.com/95004531/211740009-12dbee85-1992-405f-a146-166005af2be9.png)

**Comment by 15168440402** [comment]
那时候需求里用户列表是除外的，用户列表的创建人就是用户昵称

**Comment by 15168440402** [comment]
@xie1wei2

**Comment by xie1wei2** [comment]
第三方平台创建人错误是一个很小概率的事件，一般正常显示员工昵称。正常用户不太可能创建第三方用户！如果是第三方平台创建过来，那么该处可以为空！例如MC创建的第三方用户，创建者应该是MC中创建该用户的员工。

**Comment by LazyEar0** [comment]
@xie1wei2  确认此需求，如第三方平台用户创建人为空，此列表中创建人字段是否有意义

**Comment by xie1wei2** [comment]
取消第三方创建人字段
