### ISSUE TITLE
The Set Permission page menu is inconsistent with the Permission list menu

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#674]
Auth设置权限页有一级菜单“查询”，进入权限列表，没有一级菜单“查询”
![image](https://user-images.githubusercontent.com/95004531/212266109-1388f1d8-aed4-4ad1-a021-26af81916621.png)
![image](https://user-images.githubusercontent.com/95004531/212266164-78bb3802-6084-4213-b25b-468b1b8e9c6e.png)

**Comment by 15168440402** [comment]
无法复现
