### ISSUE TITLE
You are advised to set the minimum number of accounts to 4 digits

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#679]
账号最小限制建议调整至4位
![image](https://user-images.githubusercontent.com/95004531/212276142-2a9a4d19-a28e-4a13-90b1-25d14597d0f0.png)

**Comment by xie1wei2** [comment]
账号与密码限制安全系数较高的情况下是8位，如果特殊应用需求可以改为最小限制的4位账号。
