### ISSUE TITLE
The user sets permissions, and after selecting a team, the permissions are not filtered based on the selected team

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#681]
用户设置权限，选择团队后，权限没有根据选择的团队过滤
![image](https://user-images.githubusercontent.com/95004531/212290894-2ba7edc3-9463-4b75-a7bf-5d8b2d7e54b0.png)

**Comment by 15168440402** [comment]
测试是ok的，不选是代表所有团队的权限总和，选了是代表指定团对的权限
