### ISSUE TITLE
MC Users who add external members to the Auth should go to the third party users list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#685]
MC添加外部成员进入Auth的用户，应进入到第三方用户列表
![image](https://user-images.githubusercontent.com/95004531/212333263-bd2d7825-da5f-4238-ac76-891e88990ab3.png)

**Comment by 15168440402** [comment]
@xie1wei2

**Comment by masastack-opensource** [comment]
没必要如此设计
