### ISSUE TITLE
When you create an employee to submit, a message is displayed indicating that the employee already exists and cannot submit

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#720]
新建员工提交时，提示员工已存在，无法提交
![image](https://user-images.githubusercontent.com/95004531/221780773-d99af95d-f587-4f65-8735-4c7234150af4.png)

**Comment by MapleWithoutWords** [comment]
the bug can't reoccurrence. I local enviropement run's no problem

**Comment by wuweilaiya** [comment]
应该是身份证号已经在auth中存在了

**Comment by MapleWithoutWords** [comment]
> 应该是身份证号已经在auth中存在了

@wuweilaiya 身份证号存在，我本地提示是正常的，会提示身份证已存在

**Comment by LazyEar0** [comment]
已提示，身份证号已存在
