### ISSUE TITLE
When an error message is displayed, the data will be cleared

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#739]
新建用户/员工，最后一步弹出错误信息后，会自动回到第一步，并清空已填写的内容。(新建角色也存在此问题)
应在最后一步弹出错误信息，且不清空已填写的内容
![image](https://user-images.githubusercontent.com/95004531/222698960-251b98b5-4c65-464e-ba7b-cf2e9270b85f.png)

**Comment by MayueCif** [comment]
提交直接Throw Exception 测试该问题
