### ISSUE TITLE
If a write operation is triggered by the guest account, the popup will close automatically

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#741]
guest账号，新建自定义登录，输入内容后，点击提交按钮，弹窗会自动关闭再次打开，点击弹窗任一区域，弹窗会被关闭

https://user-images.githubusercontent.com/95004531/222705195-088c052d-6e27-466b-bfb9-4e6575628c51.mp4

**Comment by MayueCif** [comment]
应该是没动过的代码 确认是否为组件更新引起的问题

**Comment by zyz** [comment]
The development environment unable reappear

**Comment by LazyEar0** [comment]
@zyz  demo站点仍存在此问题

**Comment by zyz** [comment]
#773 delete dialog @key
