### ISSUE TITLE
Auth-角色权限UI细节优化

### ISSUE THREAD

**Issue by judyjudy2021** [masastack/MASA.Auth#749]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/81218117/223307136-c5183827-3876-436a-90cb-4ca59a49afa4.png">

**Comment by MapleWithoutWords** [comment]
the issues already modification compelete by 【kogel-net】

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/235080373-d3c74318-da6f-4218-96c9-61a9abdfaa2d.png)

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/8e80a883-6f4b-4593-8325-653bca0b74df)
