### ISSUE TITLE
Check if the mapping section is correct，section name is [ConfigurationApi:public-$Config:$public.Email]

### ISSUE THREAD

**Issue by vince0823** [masastack/MASA.Auth#762]
我将项目clone下来后。修改了Masa.Auth.Service.Admin 项目下的launchSettings.json文件下关于redis的配置以及sql连接配置。启动项目后报上述错误。我看了masa.framawork中ServiceCollectionExtensions.cs并不理解这个错误是如何引起的。麻烦看到后请告诉我如何解决这个错误。

**Comment by doddgu** [comment]
暂时先关闭这个issue，如有疑问可以reopen
