### ISSUE TITLE
The field name in the prompt must be the same as the actual field name

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#776]
提示语的字段名称要与实际字段名称保持一致，此类问题请全局自查。包括英文状态下。
![image](https://user-images.githubusercontent.com/95004531/224623771-3b9a5c6b-8186-4db9-ba11-aca592c965a8.png)

**Comment by xyfy** [comment]
![image](https://user-images.githubusercontent.com/7838147/225536424-1cd9eb94-e67e-4e72-b300-587d7de25455.png)
![image](https://user-images.githubusercontent.com/7838147/225536505-117a47ab-82ba-4726-a53e-dceec7d657f7.png)
