### ISSUE TITLE
After an employee uploaded a profile picture, the profile picture in the user table was damaged.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#781]
员工上传头像后，用户表中头像破损。
头像破损：用户列表，编辑用户，个人信息-用户身份，右上角头像；
头像正常：员工列表，编辑员工，个人信息-员工身份；
![image](https://user-images.githubusercontent.com/95004531/224643767-ecb7f217-1b0e-4820-9e6d-1f11480b8452.png)
![image](https://user-images.githubusercontent.com/95004531/224643798-63e7ccdb-fb64-48e1-bc00-657eac8cce9f.png)

**Comment by MapleWithoutWords** [comment]
the question is have not problem

**Comment by LazyEar0** [comment]
此问题仍存在
