### ISSUE TITLE
After the domain account is successfully synchronized, the pop-up window of the domain account is closed, and the third-party user list is not automatically updated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#782]
域账号同步成功后，关闭域账号弹窗，没有自动更新第三方用户列表，需要手动刷新后才显示同步的用户数据
![image](https://user-images.githubusercontent.com/95004531/224648217-a0d580a6-2cbf-4003-8ef2-83014ae618a4.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.Auth/assets/93168234/d2ddf112-af13-4256-9318-2f57998073f8)
没刷新， 还是需要手动刷新

**Comment by masastack-opensource** [comment]
没必要，后续做成异步去同步数据，建议手动刷新
