### ISSUE TITLE
The user cannot be queried by Autocomplete

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#783]
Autocomplete查询不到用户：
1.输入用户全称，查询不到结果；
2.逐字输入用户名字，会显示每一个字的搜索结果；
3.搜索结果应根据匹配度排序，匹配度高的显示在前面
![image](https://user-images.githubusercontent.com/95004531/224649908-3b5eec26-3747-4e4a-935d-2a48b8070ada.png)

**Comment by kogel-net** [comment]
(https://github.com/masastack/MASA.Stack.Components/pull/406)
