### ISSUE TITLE
Permission information, attached role should be label style

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#787]
权限信息，挂靠角色应是标签的样式
实际结果：
![image](https://user-images.githubusercontent.com/95004531/224665813-5e9bcedd-1b42-40b0-94f6-3b1d9989ce9f.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/224666047-5338fbb8-5357-4642-9446-a3261a13733f.png)

**Comment by xyfy** [comment]
resolved by pr #774
