### ISSUE TITLE
Permission list. The plus sign of the new permission is fixed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#789]
权限列表，新建权限的加号位置固定
实际结果：
![image](https://user-images.githubusercontent.com/95004531/224669130-9a3f475d-6b6f-46db-89ad-ff25c4b31ad1.png)
![image](https://user-images.githubusercontent.com/95004531/224669205-b8efe672-9435-41a1-a8a1-aceed37f9b3e.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/224669274-d252ac15-02b3-48c2-8888-0c96fb0a86d4.png)

**Comment by kogel-net** [comment]
#805
