### ISSUE TITLE
Modify the menu permission level to be the same as the element permission level

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#791]
修改菜单权限层级，可修改至与元素权限同一层级
![image](https://user-images.githubusercontent.com/95004531/224674338-85ed9ce1-f1f7-406f-9d5f-861b8701c6d6.png)
![image](https://user-images.githubusercontent.com/95004531/224674849-301dfff6-f0b6-4acd-9a3a-0dfa4a46a43f.png)

**Comment by kogel-net** [comment]
#802

**Comment by LazyEar0** [comment]
修改元素权限的位置，也可修改至与菜单权限同一层级，需要一并调整

**Comment by LazyEar0** [comment]
待 #824  修复后验证
