### ISSUE TITLE
Create a new front-end permission and the default URL prefix. In the permission information page, the URL prefix disappears

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#793]
新建前端权限，URL默认前缀，在权限信息页，URL前缀消失
![image](https://user-images.githubusercontent.com/95004531/224873361-c3c80925-4bb7-4b96-ba59-656f7b7c1acc.png)
![image](https://user-images.githubusercontent.com/95004531/224873560-b14446a3-bcd7-4b00-a595-5599e6871ae0.png)

**Comment by zyz** [comment]
#807 STextField Url add Prefix
