### ISSUE TITLE
How to deploy independently？

### ISSUE THREAD

**Issue by fanslead** [masastack/MASA.Auth#795]
I just want to deploy auth service, but it need dcc service.

**Comment by doddgu** [comment]
Yes, it depend on pm and dcc.
PM provide projects info, and dcc provide config and I18n.
So, unless you can modify its dependencies, it will not work independently.

**Comment by fanslead** [comment]
Can you tell me how to modify its dependencies? what's can remove?

**Comment by doddgu** [comment]
MASA Stack projects call each other through the project's SDK.
So you can replace the SDK implement, it could be your service's SDK, and it could be hard code logic in memory.

**Comment by fanslead** [comment]
How to do it? your document is too simple and crude.

**Comment by doddgu** [comment]
Currently, no plans to write the SDK document. But, SDK is in the MASA Framework, it's and open source project.

**Standalone deployments are not recommended!**

**Comment by fanslead** [comment]
I am trying to research the availability of Masa.Auth and at the moment, I just want to locally launch the service to see the results.
If it's necessary to fully launch all services in order to run, then I think it's too bloated.

**Comment by doddgu** [comment]
Minimum startup includes pm, auth and dcc.
MASA Stack is a stack not a project.
Our scenario is solve complex distributed project problems rather than monolith.

**Comment by fanslead** [comment]
![image](https://user-images.githubusercontent.com/22066473/224885271-96011ea6-5fb7-4798-b6bc-6d20dd0596b1.png)
But your helm chart doesn't work.

**Comment by doddgu** [comment]
@mixvii hi, PTAL

**Comment by doddgu** [comment]
> But your helm chart doesn't work.

Hi, we're writing new helm script. There's something wrong with the current version, sorry.

**Comment by fanslead** [comment]
None of this works.very disappointed

**Comment by doddgu** [comment]
Now is preview, just provide demo site to experience. We'll publish rc version by the end of March. The version of rc is goting to be stable.
