### ISSUE TITLE
Confirm the permission URL field requirements

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#796]
@xie1wei2 权限 URL字段需求确认
1.前端权限 - 菜单权限 ，父级的URL字段的逻辑需确认；
2.前端权限 - 元素权限，URL 和 挂靠API权限 优先级确认；
3.API权限 ，URL 是否需要加上路由前缀。

**Comment by MayueCif** [comment]
@xie1wei2
