### ISSUE TITLE
Update client, tab switch width should be the same width

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#798]
更新客户端，tab切换宽度应是同一宽度
实际结果：
![image](https://user-images.githubusercontent.com/95004531/224886734-d6284e98-be62-4cf5-b3d7-e0400f3c0614.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/224886809-c7afb890-76b2-4c67-af36-f00c3317c6b8.png)

**Comment by zyz** [comment]
#807 [Client dialog] SElevationTab Item add style padding
![图片](https://user-images.githubusercontent.com/714535/224977405-74a9b40c-d9b2-45b2-b92a-755f56cf0b09.png)
