### ISSUE TITLE
Edit client, change the popover title to "Edit Client"

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#799]
编辑客户端，弹窗标题修改为“编辑客户端”
![image](https://user-images.githubusercontent.com/95004531/224887027-037c6d30-3457-488b-8af5-02b6758558e6.png)

**Comment by MayueCif** [comment]
全局检索一下 更新XXX 全部替换为编辑XXX

**Comment by zyz** [comment]
#807 i18n zh-CN.json modify key [Edit Client] value
