### ISSUE TITLE
The SSO client accesses the token life cycle. Refreshing the token life cycle does not take effect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#801]
SSO 客户端访问令牌生命周期，刷新令牌生命周期不生效
![image](https://user-images.githubusercontent.com/95004531/224907535-190bb4f7-9783-4b43-8330-9c837e8c78aa.png)

**Comment by wzh425** [comment]
目前只有spa类型的客户端才有令牌配置

**Comment by limei7** [comment]
已修复
