### ISSUE TITLE
Masa Stack Compontent environment switching should be optional. And SSO page should be the same

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.Auth#806]
![image](https://user-images.githubusercontent.com/42963214/224958289-b3a1daec-f6e4-43df-b94e-2a80c2c67159.png)
![image](https://user-images.githubusercontent.com/42963214/224958374-89fdaf96-b234-464c-96a0-52e54d386c2a.png)

**Comment by MayueCif** [comment]
stack component 增加一个属性是否展示多环境切换，默认值false,隐藏左侧环境切换功能。并判断只有一个环境时隐藏切换功能。
sso登陆页判断只有一个环境时隐藏环境切换功能

**Comment by codding-y** [comment]
> 

That sounds good
