### ISSUE TITLE
Description When creating a user, the built-in text in the nickname text box is not fully displayed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#830]
新建用户，昵称文本框内置文字显示不全
![image](https://user-images.githubusercontent.com/95004531/225567157-9f82a56b-717e-47b1-bd30-919de6d94f5d.png)

**Comment by xyfy** [comment]
it is fixed in pr  #817

**Comment by xyfy** [comment]
![image](https://user-images.githubusercontent.com/7838147/225800860-8b8ac591-7d23-4b98-9bb4-6647ba932e92.png)

**Comment by xyfy** [comment]
I will take a check the inpu style with design
