### ISSUE TITLE
Create a new/edit team with the team name centered

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#837]
新建/编辑团队，团队名称应居中
实际结果：
![image](https://user-images.githubusercontent.com/95004531/225847689-addeee76-c122-4781-bd7b-c4c3b16be888.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/225847739-a0248030-06c5-4da1-9acf-9ed2fc64dd91.png)

**Comment by xyfy** [comment]
resolve in https://github.com/masastack/MASA.Auth/pull/836
