### ISSUE TITLE
Auth-UX全局通用-单点登录、消息中心

### ISSUE THREAD

**Issue by judyjudy2021** [masastack/MASA.Auth#845]
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/81218117/226303951-2ea6dd8a-0b4d-408a-b601-ab7add2ad366.png">

**Comment by LazyEar0** [comment]
下拉菜单实际效果与设计稿不符
实际效果
![image](https://user-images.githubusercontent.com/95004531/235081807-9029b46e-109e-43c8-9a35-05569479944b.png)
预期效果
![image](https://user-images.githubusercontent.com/95004531/235081974-ab3bbc4d-26e6-48d9-986d-b6b7fdff3c87.png)
