### ISSUE TITLE
After you log out, the environment switchover is invalid

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#863]
退出登录后，切换环境无效
![image](https://user-images.githubusercontent.com/95004531/227408250-2bb56fdf-fc49-470a-970a-098466d3ad95.png)

https://user-images.githubusercontent.com/95004531/227409197-1fd8ad49-506e-4490-a075-759c49b982cc.mp4

**Comment by MayueCif** [comment]
这个应该不是必现bug
