### ISSUE TITLE
 state

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.Auth#88]
![image](https://user-images.githubusercontent.com/102500164/169739732-6b3c0abd-b67a-4e62-815d-63c33bf16b39.png)
![image](https://user-images.githubusercontent.com/102500164/169739871-c3e054e2-6dfc-461a-89a3-b0c97b92ecaf.png)
与UI界面不一致

**Comment by 15168440402** [comment]
就用这个ui
