### ISSUE TITLE
The new team button is slow to load

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#909]
新建团队按钮点击后，弹窗加载过慢

https://user-images.githubusercontent.com/95004531/230266285-4ed9115d-683f-4619-a7d7-b33ff888800f.mp4

**Comment by LazyEar0** [comment]
新建用户，新建员工，新建角色，授权页 同样存在此问题

**Comment by MayueCif** [comment]
[#MASA.Blazor 1359](https://github.com/masastack/MASA.Blazor/issues/1359)
