### ISSUE TITLE
Permissions. The search icon and text are not aligned

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#913]
权限。搜索icon和文本没有对齐
![image](https://user-images.githubusercontent.com/95004531/230297337-6324ac08-0b43-4df0-a57e-faf2c2acbe0a.png)

**Comment by MayueCif** [comment]
统一检查Auth中搜索框替换为Stack Component里搜索框

**Comment by zyz** [comment]
#930 Search box

**Comment by zyz** [comment]
@MayueCif Permissions
