### ISSUE TITLE
Operation log, after selecting time, should add clear button

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#921]
操作日志，选择时间后，应增加清除按钮，点击后，清除下拉框的数据
![image](https://user-images.githubusercontent.com/95004531/230329791-c332c66b-b551-49d8-b6f0-ed501f7a93c3.png)

**Comment by kogel-net** [comment]
https://github.com/masastack/MASA.Stack.Components/pull/475

**Comment by kogel-net** [comment]
#957

**Comment by LazyEar0** [comment]
下拉框未选择数据时，不需要清除按钮
![image](https://user-images.githubusercontent.com/95004531/231660678-4880c2ed-1ee6-4864-ad1d-100763faff0d.png)

**Comment by MayueCif** [comment]
整体更换组件
