### ISSUE TITLE
After the user logs in, the environment displays an error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#932]
登录界面选择staging环境，成功登录后，左侧菜单下方的环境显示为development，且退出登录至登录页面后，环境选择下拉框内显示的环境也是development，应是staging。
![image](https://user-images.githubusercontent.com/95004531/230554978-4dc08ba8-4dab-4485-a84d-12746f1974e4.png)
![image](https://user-images.githubusercontent.com/95004531/230554997-e489363f-8a26-4e7f-886e-317a4126221f.png)
![image](https://user-images.githubusercontent.com/95004531/230555026-1d037069-7c54-4f0e-98a1-9573f325d7b6.png)

**Comment by limei7** [comment]
retest ok
