### ISSUE TITLE
User associated role saving is not valid

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#936]
用户关联角色，第一次打开授权弹窗，选择角色保存成功。再次打开弹窗，上一次关联的角色未成功保存。第二次关联角色方成功保存。
![image](https://user-images.githubusercontent.com/95004531/230814808-960a5afd-8df7-42ed-ba67-9e8f3ce9fcb1.png)

**Comment by binwan-dev** [comment]
等待测试环境测试后进一步调整
