### ISSUE TITLE
按钮文字、Tabs文字，首字母大写

### ISSUE THREAD

**Issue by judyjudy2021** [masastack/MASA.Auth#941]
<img width="834" alt="企业微信截图_89d0069a-3a50-46d2-9947-4916a40243bd" src="https://user-images.githubusercontent.com/81218117/231048331-96493fe5-809e-404e-b95e-726822f7e0f7.png">
<img width="497" alt="企业微信截图_b101eec8-013c-47e7-9be3-d8d809e49b31" src="https://user-images.githubusercontent.com/81218117/231048336-6a8b816c-9cca-41b5-b0ef-2d4985c84d77.png">

**Comment by doddgu** [comment]
这个是masa blazor的 @capdiem PTAL

**Comment by capdiem** [comment]
@doddgu 不能随便换成 MD3 的吧，而且我也没有这个能力改这么多CSS。

**Comment by doddgu** [comment]
按钮和Tabs把 text-uppercase 改成 text-capitalize 就可以了

**Comment by limei7** [comment]
OK
