### ISSUE TITLE
Custom registration, the phone number is truncated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#944]
自定义注册，手机号码被截断
![image](https://user-images.githubusercontent.com/95004531/231050667-5533a6be-242a-4611-a8c7-54544735b57b.png)

**Comment by LazyEar0** [comment]
此问题仍存在
![image](https://user-images.githubusercontent.com/95004531/232651431-1031c311-ea81-4cfd-bd63-9ace37a77d30.png)

**Comment by zyz** [comment]
#1108
