### ISSUE TITLE
Custom login, registration page field header error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#945]
自定义登录，注册页字段表头错误，应为“名称”
![image](https://user-images.githubusercontent.com/95004531/231050796-acdac926-823f-4d26-8ba9-36745cd1b58e.png)

**Comment by MayueCif** [comment]
单独增加一个i18n key

**Comment by zyz** [comment]
#955

**Comment by LazyEar0** [comment]
自定义登录基础信息和列表也需要修改
![image](https://user-images.githubusercontent.com/95004531/231662968-3b66880b-1c97-491d-bdad-e64509faea64.png)

![image](https://user-images.githubusercontent.com/95004531/231662879-41985754-c206-4182-8838-276472ebb67c.png)

**Comment by zyz** [comment]
#1004
