### ISSUE TITLE
Menu permissions change location to root directory, error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#949]
添加api权限/一级菜单/菜单权限修改位置至根目录下，报错
![image](https://user-images.githubusercontent.com/95004531/231073217-32a1c76e-6c4a-4928-836b-e03cd523bb3a.png)

![image](https://user-images.githubusercontent.com/95004531/231071840-ec0899fe-39c6-495a-ab61-bd8c02f4ff93.png)
![image](https://user-images.githubusercontent.com/95004531/231072005-cacb2890-6f3b-44a0-80af-9e05a5c49885.png)

**Comment by xyfy** [comment]
#1003
