### ISSUE TITLE
Loss of user privileges

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#952]
用户账号：fengbaobao  在团队“wst-team3”中，团队有权限，用户没有权限
用户权限：
![image](https://user-images.githubusercontent.com/95004531/231081543-0a741ede-684c-4ad9-a87d-9961d3e056fa.png)
所在团队权限：
![image](https://user-images.githubusercontent.com/95004531/231081671-cae8f470-f29e-49e5-9a8b-8ac95aa61ffa.png)
![image](https://user-images.githubusercontent.com/95004531/231081714-d9fde687-776f-4359-9fc8-10c877b8c3f2.png)
![image](https://user-images.githubusercontent.com/95004531/231081771-21685267-a935-4dec-85a4-b5b8e3216174.png)

**Comment by MayueCif** [comment]
用户编辑页面 修改所在团队是，更新团队缓存
