### ISSUE TITLE
In MC Chinese state, global navigation enters Auth and i18n changes to English

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#956]
MC 中文状态下，全局导航进入Auth，i18n 变为英文
![image](https://user-images.githubusercontent.com/95004531/231127495-e3d16db2-6c49-4c64-bab2-1fff48f9d20b.png)

**Comment by MapleWithoutWords** [comment]
猜测可能是BlazorComponent系统默认的语言项没更新，第二次设置失败，就取得默认的英文。PR：https://github.com/masastack/BlazorComponent/pull/379

**Comment by MapleWithoutWords** [comment]
需等待Masa.Blazor发版。当前版本：preview.14，等待发布preview.15或更高

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by wzh425** [comment]
等待下次更新MASA.Stack.Components
