### ISSUE TITLE
Custom login - registration, when verifying the user password, should be in the "User password" text box verification

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#981]
自定义登录-注册，验证用户密码时，应在“用户密码”文本框验证，“确认密码”文本框只需验证是否与用户密码一致，不需要验证密码规则
![image](https://user-images.githubusercontent.com/95004531/231662215-dce5eef6-a5cb-4557-a4fd-ee4d52da1601.png)

**Comment by binwan-dev** [comment]
[PR-985](https://github.com/masastack/MASA.Auth/pull/985)
