### ISSUE TITLE
Custom login - Login, only need to verify that the password is correct, do not need to verify that the password conforms to the rules

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#982]
自定义登录-登录，只需要验证密码是否正确，不需要验证密码是否符合规则
![image](https://user-images.githubusercontent.com/95004531/231662429-04d3bec4-7a70-4e95-a8bc-808de35a7aca.png)

**Comment by MayueCif** [comment]
只验证密码和确认密码是否相同，不验证密码规则

**Comment by zyz** [comment]
#1004
