### ISSUE TITLE
Custom Login - Register, action button newline, should be displayed in one line

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Auth#986]
自定义登录-注册，操作按钮换行，应显示在一行，背景偏移了
![image](https://user-images.githubusercontent.com/95004531/231726617-60437230-4b99-43dc-a8af-9c81c4d057ae.png)
![image](https://user-images.githubusercontent.com/95004531/231727640-97f6765e-1fe9-430a-96fd-df0818593d81.png)

**Comment by kogel-net** [comment]
https://github.com/masastack/MASA.Auth/pull/988
